### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by asbjornenge** [prg3/cgminer_exporter#2]
Hi!

Thanks for sharing this exporter 👍 

Do you have a grafana or similar dashboard you are using to display all the metrics that you could also share? If you are using grafana you can dump the json for a dashboard to share 😉 

Kind regards,
Asbjorn

**Comment by prg3** [comment]
Just uploaded one of the dashboards I am using.. the other summary board has a lot of other things on it but I'll see if I can break that one up to something useful here.

**Comment by asbjornenge** [comment]
Fantastic!! Thanks a bunch 😬  🙌🎉

I'll close this issue now, but please ping me here if you get around to break out the summary dash 👌

**Comment by asbjornenge** [comment]
@prg3 did you get a chance to look at that summary board? If there is nothing sensitive in there feel free to add it as-is in a branch or something and I can clean it up for your 😉 👍
